# Generated by Django 5.0.4 on 2024-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
